# set CUSTOM_NETWORK_NAME to the name of the custom Docker network
version: "3"
services:
  elasticsearch:
    image: elasticsearch:2.1.1
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - ${CUSTOM_NETWORK_NAME}
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  logstash:
    image: accenture/adop-logstash:0.1.0
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - ${CUSTOM_NETWORK_NAME}
    environment:
      - "constraint:tier==public"
      - LS_HEAP_SIZE=1024m
    ports:
      - "12201:12201/udp"
      - "25826:25826/udp"
      - "5000:5000/tcp"

  kibana:
    image: kibana:4.3.1
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - ${CUSTOM_NETWORK_NAME}
    command: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
